=== PCJIC/-MunozLaura_Ejercicio2_Taller1_CES3/ListaPedidos.dtd
<!ELEMENT ListaPedidos (Pedido)*>
        <!ELEMENT Pedido (NumeroSerie, Cantidad, Peso*)>
        <!ELEMENT NumeroSerie (#PCDATA)>
        <!ELEMENT Cantidad (#PCDATA)>
        <!ELEMENT Peso (#PCDATA)>

=== PCJIC/-MunozLaura_Ejercicio2_Taller1_CES3/ListaPedidos.xml
<?xml version="1.0" encoding="UTF-8" ?>

<!DOCTYPE ListaPedidos SYSTEM "ListaPedidos.dtd">

<ListaPedidos>
    <Pedido>
        <NumeroSerie>1010</NumeroSerie>
        <Cantidad>2</Cantidad>
        <Peso>3 kg</Peso>
    </Pedido>
    <Pedido>
        <NumeroSerie>1020</NumeroSerie>
        <Cantidad>8</Cantidad>
    </Pedido>
    <Pedido>
        <NumeroSerie>1030</NumeroSerie>
        <Cantidad>2</Cantidad>
    </Pedido>
    <Pedido>
        <NumeroSerie>1040</NumeroSerie>
        <Cantidad>2</Cantidad>
        <Peso>3 kg</Peso>
    </Pedido>
</ListaPedidos>
